### ISSUE TITLE
Engine breaks when gridTemplateRows and gridTemplateColumns are not provided for the grid container.

### ISSUE THREAD

**Issue by priyanjitdey94** [fusioncharts/faberjs#19]

**Comment by sidhartha-fusioncharts** [comment]
Updating the default value for tracks from 'auto' to '[one] auto' resolves the issue. 
In line no. 134 in [grid/index.js](https://github.com/fusioncharts/mason/blob/develop/src/grid/index.js)
`_fetchTrackInformation (tracks = 'auto') {` 
to `_fetchTrackInformation (tracks = '[one] auto') {` 
saves the engine from breaking

**Comment by sidhartha-fusioncharts** [comment]
Changing the default value for tracks from 'auto' to '[one] auto' resolves the issue.
In line 134 [grid/index.js](https://github.com/fusioncharts/mason/blob/develop/src/grid/index.js)
from `https://github.com/fusioncharts/mason/blob/develop/src/grid/index.js`
to `_fetchTrackInformation (tracks = '[one] auto') {` 
saves the engine from breaking

**Comment by siddharthapaul001** [comment]
Please check it [here](https://github.com/fusioncharts/mason/pull/20)

**Comment by priyanjitdey94** [comment]
[PR 20](https://github.com/fusioncharts/mason/pull/20) is a proper fix for this issue. @siddharthapaul001  Thanks for this. Resolving this issue.
