### ISSUE TITLE
Support multiple names of a grid line

### ISSUE THREAD

**Issue by priyanjitdey94** [fusioncharts/faberjs#23]
`gridTemplateColumns: [one] auto [two] auto [three] // works`
`gridTemplateColumns: [one] auto [two two-dash] auto [three] // won't work`

The 2nd grid lines should take up both the names(`two` and `two-dash`).

**Comment by siddharthapaul001** [comment]
The issue raised due to the regular expression `templateSplitRegex`. I've modified it. Please check #27

**Comment by priyanjitdey94** [comment]
#27 fixed this. Closing.
