### ISSUE TITLE
Support `gridRow` and `gridColumn` properties

### ISSUE THREAD

**Issue by priyanjitdey94** [fusioncharts/faberjs#25]
Only the following grid item placement properties are supported as of now:
1. `gridColumnStart`
2. `gridColumnEnd`
3. `gridRowStart`
4. `gridRowEnd`

`gridRow` and `gridColumn` attribute should also be supported and should accept all the standard inputs. For example,
```
gridColumn: 'start-line / end-line'; // start-line and end-line are line names
gridColumn: 'start-line / 4';        // 4 is the line number
gridColumn: '2 / span 2';            // start from line 2 and span up to the next 2 lines
```

**Comment by siddharthapaul001** [comment]
Please check #27

**Comment by priyanjitdey94** [comment]
PR #27 is merged. Closing this issue.
